version: "3"
services:
  app:
    container_name: "bot_app"
    build: ./app
  pg:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - "POSTGRES_PASSWORD=root_password"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=db"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data